const prisma = require('../prisma');
const { createSimplePdf } = require('../utils/simplePdf');

const toNumber = (value) => Number(value || 0);
const formatMoney = (value, currency = 'UGX') => `${toNumber(value).toLocaleString('en-UG')} ${currency}`;
const formatDate = (value) => new Date(value).toLocaleDateString('en-UG');
const formatDateTime = (value) => new Date(value).toLocaleString('en-UG');

class PaymentReceiptService {
  async getPaymentReceiptData({ paymentId, vendorId = null }) {
    const payment = await prisma.invoicePayment.findUnique({
      where: { id: paymentId },
      include: {
        vendor: true,
        allocations: {
          include: {
            invoice: true,
          },
        },
        paymentAttempt: true,
      },
    });

    if (!payment) {
      throw new Error('Payment receipt source payment not found.');
    }

    if (vendorId && payment.vendorId !== vendorId) {
      throw new Error('Unauthorized to access this payment receipt.');
    }

    if (payment.status !== 'CONFIRMED') {
      throw new Error('Receipt is only available for confirmed payments.');
    }

    return payment;
  }

  buildReceiptNumber(payment) {
    return `RCT-${payment.id.slice(0, 8).toUpperCase()}`;
  }

  buildReceiptLines(payment) {
    const receiptNumber = this.buildReceiptNumber(payment);
    const lines = [
      'MMIS PAYMENT RECEIPT',
      '',
      `Receipt Number: ${receiptNumber}`,
      `Payment ID: ${payment.id}`,
      `Vendor: ${payment.vendor.businessName}`,
      `Payment Date: ${formatDateTime(payment.paymentDate)}`,
      `Recorded At: ${formatDateTime(payment.createdAt)}`,
      `Amount Received: ${formatMoney(payment.amount, payment.currencyCode)}`,
      `Payment Method: ${payment.paymentMethod}`,
      `Payment Channel: ${payment.paymentChannel}`,
      `Provider: ${payment.provider || 'N/A'}`,
      `Provider Reference: ${payment.providerReference || payment.paymentAttempt?.attemptReference || 'N/A'}`,
      '',
      'Invoice Allocations:',
      ...(payment.allocations.length
        ? payment.allocations.map((allocation) => (
            `- ${allocation.invoice.invoiceNumber || allocation.invoice.id} | `
            + `${allocation.invoice.billingYear}-${String(allocation.invoice.billingMonth).padStart(2, '0')} | `
            + `Due ${formatDate(allocation.invoice.dueDate)} | `
            + `${formatMoney(allocation.allocatedAmount, payment.currencyCode)}`
          ))
        : ['- No invoice allocations found']),
      '',
      `Total Allocated: ${formatMoney(payment.allocations.reduce((sum, allocation) => sum + toNumber(allocation.allocatedAmount), 0), payment.currencyCode)}`,
      '',
      'Notes:',
      payment.notes || 'No additional notes',
      '',
      'This receipt is generated by MMIS from a confirmed payment record.',
    ];

    return { receiptNumber, lines };
  }

  async generatePaymentReceiptPdf({ paymentId, vendorId = null }) {
    const payment = await this.getPaymentReceiptData({ paymentId, vendorId });
    const { receiptNumber, lines } = this.buildReceiptLines(payment);

    return {
      fileName: `${receiptNumber}.pdf`,
      buffer: createSimplePdf(lines),
      payment,
      receiptNumber,
    };
  }
}

module.exports = new PaymentReceiptService();
